apis/ruby/rails-example/master/config/routes.rb
HerokuPrime::Application.routes.draw do
  resources :documents
  resources :datasets
  root :to => redirect('/documents')

end

apis/ruby/rails-example/master/app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :title, :source_url, :body
end

apis/ruby/rails-example/master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def max_title_len
    45
  end
  
  def set_title(str)
    str = str.strip
    @title = str[0, max_title_len]
    @title << '...' if str.length > max_title_len
  end
end

apis/ruby/rails-example/master/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = Document.all
  end
  
  def show
    @doc = Document.find_by_id(params[:id])
    set_title @doc.title 
  end
  
  def new
  end
  
  def create
    @doc = Document.create!(params[:doc])
    redirect_to documents_path
  end
  
  def delete
  end
end

apis/ruby/rails-example/master/app/helpers/application_helper.rb
module ApplicationHelper
end

apis/ruby/rails-example/master/app/views/datasets/index.html.haml
%h2 Stored documents

%table#docs
	%thead
		%th= link_to "+", new_document_path
		%th ID
		%th Name
		%th # of Docs
		%th
	%tbody
		- @datasets.each do |dataset|
			%tr
				%td
				%td= dataset.id
				%td= dataset.name
				%td= dataset.size
				%td= link_to "details...", dataset_path(dataset)

apis/ruby/rails-example/master/app/views/datasets/new.html.haml
%h2 Add dataset

= form_tag documents_path, :method => :post do
	= label :doc, :title, 'Title'
	= text_field :doc, :title
	
	= label :doc, :source_url, 'URL'
	= text_field :doc, :source_url

	= label :doc, :body, 'Body'
	= text_area :doc, :body
	
	= submit_tag 'Save'

apis/ruby/rails-example/master/app/views/datasets/show.html.haml
%h2 Document
%a{:href => documents_path()}
	Back to list of Documents

%h3= @doc.title
%p.source= @doc.source_url

%div.doc_body
	= @doc.body

apis/ruby/rails-example/master/app/views/documents/index.html.haml
%h2 Stored documents

%table#docs
	%thead
		%th= link_to "+", new_document_path
		%th Title
		%th Length
		%th URL
		%th
	%tbody
		- @documents.each do |doc|
			%tr
				%td
				%td= doc.title
				%td= doc.body.length
				%td= doc.source_url
				%td= link_to "details...", document_path(doc)

apis/ruby/rails-example/master/app/views/documents/new.html.haml
%h2 Add document

= form_tag documents_path, :method => :post do
	= label :doc, :title, 'Title'
	= text_field :doc, :title
	
	= label :doc, :source_url, 'URL'
	= text_field :doc, :source_url

	= label :doc, :body, 'Body'
	= text_area :doc, :body
	
	= submit_tag 'Save'

apis/ruby/rails-example/master/app/views/documents/show.html.haml
%h2 Document
%a{:href => documents_path()}
	Back to list of Documents

%h3= @doc.title
%p.source= @doc.source_url

%div.doc_body
	= @doc.body

apis/ruby/rails-example/master/app/views/layouts/application.html.haml
%html
	%head
		%title
			= "#{@title} - " if @title != nil
			Heroku Prime project
		= stylesheet_link_tag 'application'
		= javascript_include_tag 'application'
		= csrf_meta_tags
	%body
		= yield